---
- name: UFW Playbook
  apt: pkg=ufw state=latest
  
- name: Allow ports
  ufw: rule=allow port={{item}} 
  with_items: ufw_allow_ports
  
- name: Ensure UFW Running
  ufw: state=enabled
  when: firewall_enabled==true

- name: Ensure UFW NOT Running
  ufw: state=disabled
  when: firewall_enabled==false
